config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'posts#index'
  resources :posts, only: [:index, :show, :create] do
    resources :comments
  end
  get '/creer' => 'posts#new'
  get 'posts/:id' => 'posts#show'
  get 'posts/:id/edit' => 'posts#edit'
  patch 'posts/:id' => 'posts#update'
  delete 'posts/:id' => 'posts#destroy'

  get '/users' => 'users#index'

  get 'users/:username' => 'users#show'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user

  validates :content, presence: true
end

app/models/post.rb
class Post < ApplicationRecord

  mount_uploader :image, ImageUploader

  belongs_to :user
  has_many :comments, dependent: :destroy

  # has_many :comments
  #
  # has_attached_file :image, styles: { large: '1105x300#', medium: '600x440>', thumb: '160x250#', small: '250x200#' }
  # validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

  validates :title, presence: true, uniqueness: { case_sensitive: false, message: 'Titre déja existant'}
  validates :text, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts
  has_many :comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :user
  before_action :configure_devise_parameters, if: :devise_controller?
  before_action :set_locale
  layout :layout_by_resource

  def configure_devise_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:username, :email, :password, :password_confirmation) }
  end

  def user
    @user = current_user
  end

  def layout_by_resource
    if devise_controller? && resource_name == :user && action_name == 'new'
      "light"
    else
      "application"
    end
  end

  private
  def extract_locale_from_accept_language_header
    request.env['HTTP_ACCEPT_LANGUAGE'].scan(/^[a-z]{2}/).first
  end

  def set_locale
    I18n.locale = extract_locale_from_accept_language_header || I18n.default_locale
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_action :find_post
  before_action :find_comment, only: [:destroy, :edit, :update, :comment_owner]
  before_action :comment_owner, only: [:destroy, :edit, :update]

  before_action :authenticate_user!

  def create
    @comment = @post.comments.create(comment_params)
    @comment.user_id = current_user.id
    @comment.save
    redirect_to @post
  end

  def destroy
    @comment.destroy
    redirect_to post_path(@post)
  end

  def edit
  end

  def update
    if @comment.update(comment_params)
      redirect_to post_path(@post)
    else
      render 'edit'
    end
  end


  private

  def find_post
    @post = Post.find(params[:post_id])
  end

  def find_comment
    @comment = @post.comments.find(params[:id])
  end

  def comment_params
    params.require(:comment).permit(:content)
  end

  def comment_owner
    unless current_user == @comment.user
      redirect_to @post
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action  only: [:show, :update, :update, :destroy]
  before_action :authenticate_user!

  def index
    if Post.last.nil? == false
      @latest_post = Post.last
      @posts = Post.where.not(id: @latest_post.id).order('created_at DESC')
    else
      @posts = Post.all
    end
  end

  def new
    @post = current_user.posts.build
  end

  def show
    @post = Post.find(params[:id])
    @comments = Comment.where(post_id: @post).order('created_at DESC')
  end

  def edit
    @post = Post.find(params[:id])
  end

  def create
    @post = current_user.posts.build(post_params)
    redirect_to '/' if @post.save
  end

  def update
    Post.find(params[:id]).update(post_params)
    redirect_to "/posts/#{params[:id]}"
  end

  def destroy
    Post.find(params[:id]).destroy
    redirect_to '/'
  end

  private

  def post_params
    params.require(:post).permit(:title, :text, :image)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def show
    @user = User.find_by(username: params[:username])
    @posts = @user.posts.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<div class="container add-commentaire">
  <%= render 'comments/form' %>
</div>
<div class="container liste-commentaire">
<% if @comments.count > 0 %>
  <% @comments.each do |comment| %>
    <div class="commentaire border box-shadow">
    <p><b><%= comment.user.username %></b></p>
    <p><%= comment.content.html_safe %></p>
    <% if current_user == comment.user || current_user == @post.user %>
        <div class="col-md-12 px-0 buttons">
          <%= link_to "Supprimer le commentaire", [comment.post, comment], method: :delete, class: 'btn btn-outline-warning mr-2' %>
          <%= link_to "Modifier le commentaire", edit_post_comment_path(comment.post, comment),class: 'btn btn-outline-danger' %>
        </div>
    <% end %>
    </div>
  <% end %>
<% else %>
  <p class="text-center">Aucun commentaire n'a été laissé pour l'insant</p>
<% end %>
</div>

app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build]) do |f| %>
  <%= f.trix_editor :content, label: false, placeholder: 'Ajouter votre commentaire...' %>
  <p class="text-center mt-2 mb-4"><%= f.submit "Commenter", class: 'btn btn-primary submit-button ' %></p>
<% end %>

app/views/comments/edit.html.erb
<h1 class="text-center mb-4"><%= t('modify_comment') %></h1>
<%= form_for([@post, @comment]) do |f| %>
  <%= f.trix_editor :content %>
  <p class="text-center"><%= f.submit t('validate'), class: 'btn btn-primary btn-lg submit-button mt-4' %></p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="fr">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <title><%= content_for?(:title) ? yield(:title) : "Share.it" %></title>
  <%= favicon_link_tag 'favicon.ico' %>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body class="page">
<header class="blog-header py-3 sticky-top">
  <div class="row flex-nowrap justify-content-between align-items-center">
    <div class="col-4 pt-1">
      <a href="/creer" class="btn btn-sm btn-outline-secondary pl-2 pr-2">
        <%= t('add_post')%>
      </a>
      <a href="/users/<%= current_user.username %>" class="btn btn-sm btn-outline-secondary pl-2 pr-2">
        <%= t('your_blog')%>
      </a>
    </div>
    <div class="col-4 text-center">
      <a class="blog-header-logo text-dark" href="/">Share.it</a>
    </div>
    <div class="col-4 d-flex justify-content-end align-items-center">
      <button type="button" class="btn btn-secondary btn-sm mr-1" disabled><%= current_user.username %></button>
      <%= link_to(t('log_out'), destroy_user_session_path, :class => "btn btn-sm btn-outline-secondary pl-2 pr-2", method: :delete)%>
    </div>
  </div>
</header>

<% if notice.nil? == false %>
  <div class="alert alert-success alert-dismissible fade show" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

<% if alert.nil? == false%>
  <div class="alert alert-warning alert-dismissible fade show" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<%= yield %>
<footer></footer>
</body>
</html>

app/views/layouts/light.html.erb
<!DOCTYPE html>
<html lang="fr">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <title><%= content_for?(:title) ? yield(:title) : "Share.it" %></title>
  <%= favicon_link_tag 'favicon.ico' %>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>
<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<%= simple_form_for @post , html: { multipart: true } do |f| %>

  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
        <% @post.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.input :title, label: t('title') %>
  <%= f.trix_editor :text, label: t('content') %>
  <%= f.file_field :image, label: t('image') %>
  <p class="text-center"><%= f.button :submit, t('validate'), class: 'btn btn-primary btn-lg submit-button mt-4' %></p>
<% end %>

app/views/posts/edit.html.erb
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="/"><%= t('home')%></a></li>
    <li class="breadcrumb-item"><a href="/users"><%= t('authors')%></a></li>
    <li class="breadcrumb-item"><a href="/users/<%= @user.username %>"><%= @user.username %></a></li>
    <li class="breadcrumb-item active" aria-current="page"><%= t('modify_post')%></li>
  </ol>
</nav>
<div class="modify-post">
  <h1 class="text-center"><%= t('modify_post')%></h1>
  <%= render partial: 'form' %>
</div>

app/views/posts/index.html.erb
<div class="filtre container">
  <div class="btn-group" role="group" aria-label="Basic example">
    <a href="#"><button type="button" class="btn btn-secondary active"><%= t('home') %></button></a>
    <a href="/users"><button type="button" class="btn btn-secondary"><%= t('authors') %></button></a>
  </div>
</div>

<div class="container posts">
 <% if @latest_post.nil? == false %>
  <div  class="jumbotron p-3 text-white rounded posts__big">
    <div class="col-md-12 px-0 posts__big-text">
      <h1 class="display-4 font-italic"><%= @latest_post.title %></h1>
      <p class="lead my-3"><% latestText = strip_tags(@latest_post.text) %><%= excerpt(latestText, 'is', radius: 20) %></p>
      <p class="lead my-3"><%= t('by') %> <a href="/users/<%= @latest_post.user.username %>"><%= @latest_post.user.username %></a></p>
      <p class="lead mb-0"><a href="/posts/<%= @latest_post.id %>" class="text-white font-weight-bold"><%= t('read_more') %></a></p>
    </div>
    <% if @latest_post.image? %>
      <%= image_tag @latest_post.image_url(:large), class: 'posts__big-image' %>
    <% else %>
      <img src="<%= image_path('missing-large.jpg') %>" alt="">
    <% end %>
  </div>
  <% end %>


  <div class="row mb-2">

    <% @posts.each do |post| %>
      <div class="col-md-6">
        <div class="card flex-md-row mb-4 box-shadow h-md-250">
          <div class="card-body d-flex flex-column align-items-start">
            <h3 class="mb-0">
              <p class="text-dark"><%= post.title %></p>
            </h3>
            <div class="mb-1 text-muted"><%= post.created_at.strftime("%d %B %Y") %></div>
            <p class="card-text mb-auto"><% text = strip_tags(@posts.last.text) %><%= excerpt(text, 'is', radius: 20) %></p>
            <a href="/posts/<%= post.id %>"><%= t('read_more') %></a>
          </div>
          <% if post.image? %>
            <%= image_tag post.image_url(:thumb), class: 'card-img-right flex-auto d-none d-md-block' %>
          <% else %>
            <img src="<%= image_path('missing-thumb.png') %>" alt="">
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/posts/new.html.erb
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="/"><%= t('home') %></a></li>
    <li class="breadcrumb-item"><a href="/users"><%= t('authors') %></a></li>
    <li class="breadcrumb-item"><a href="/users/<%= @user.username %>"><%= @user.username %></a></li>
    <li class="breadcrumb-item active" aria-current="page"><%= t('add_post') %></li>
  </ol>
</nav>
<div class="create-post">
  <h1 class="text-center"><%= t('add_post') %></h1>
  <%= render partial: 'form' %>
</div>

app/views/posts/show.html.erb
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="/"><%= t('home') %></a></li>
    <li class="breadcrumb-item"><a href="/users"><%= t('authors') %></a></li>
    <li class="breadcrumb-item"><a href="/users/<%= @post.user.username %>"><%= @post.user.username %></a></li>
    <li class="breadcrumb-item active" aria-current="page"><%= @post.title %></li>
  </ol>
</nav>
<div class="single-article mb-5">
  <div class="title">
    <h1><%= @post.title %></h1>
    <p class="author"><%= t('by') %> <a href="/users/<%= @post.user.username %>"><%= @post.user.username %></a></p>
  </div>
  <% if @post.user == current_user %>
    <div class="buttons">
      <a href="/posts/<%= @post.id %>/edit" class="mr-3"><button type="button" class="btn btn-outline-warning"><%= t('edit') %></button></a>
      <%= link_to 'Supprimer', @post,  method: :delete, data: { confirm: 'Êtes-vous sur ?' }, class: 'btn btn-outline-danger' %>
    </div>
  <% end %>
  <% if @post.image? %>
    <%= image_tag @post.image_url(:large), class: 'img-fluid mt-4' %>
  <% else %>
    <img src="<%= image_path('missing-large.jpg') %>" alt="">
  <% end %>
  <div class="text"><%= strip_tags(@post.text) %></div>
</div>

<% if @post.user.posts.count > 1 %>
  <h3 class="text-center mb-4"><%= t('more_posts_from_this_author') %></h3>
  <% posts = Post.where("user_id = ? AND id != ?", @post.user, @post.id) %>
  <% posts = posts.last(3) %>
     <div class="card-deck mb-5">
  <% posts.each do |post| %>
      <div class="card">
        <% if post.image? %>
          <%= image_tag post.image_url(:small), class: 'img-fluid' %>
        <% else %>
          <img src="<%= image_path('missing-small.png') %>" alt="">
        <% end %>
        <div class="card-body">
          <a href="/posts/<%= post.id %>"><h5 class="card-title"><%= post.title %></h5></a>
          <p class="card-text"><% text = strip_tags(post.text) %><%= excerpt(text, 'is', radius: 20) %></p>
          <p class="card-text"><small class="text-muted"><%= post.created_at.strftime("%d %B %Y") %></small></p>
        </div>
      </div>
      <% end %>
    </div>
<% end %>

<div class="container">
  <h3 class="text-center mb-4"><%= t('comments') %></h3>
  <%= render 'comments/comment' %>
</div>

app/views/users/index.html.erb
<div class="filtre container">
  <div class="btn-group" role="group" aria-label="">
    <a href="/"><button type="button" class="btn btn-secondary"><%= t('home') %></button></a>
    <a href="#"><button type="button" class="btn btn-secondary active"><%= t('authors') %></button></a>
  </div>
</div>
<div class="users-list container mt-4">
  <% if @users.nil? == false %>
    <ul class="list-group">
      <% @users.each do |user| %>
        <li class="list-group-item d-flex justify-content-between align-items-center">
          <a href="/users/<%= user.username %>"><%= user.username %></a>
          <span class="badge badge-primary badge-pill"><%= user.posts.count %></span>
        </li>
      <% end %>
    </ul>
  <% end %>
</div>

app/views/users/show.html.erb
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="/"><%= t('home') %></a></li>
    <li class="breadcrumb-item"><a href="/users"><%= t('authors') %></a></li>
    <li class="breadcrumb-item active" aria-current="page"><%= @user.username %></li>
  </ol>
</nav>
<div class="container single-user">
<h1 class="text-center mt-4 mb-4"><%= t('the_blog') %> <i><%= @user.username %></i></h1>
<% @posts.each do |post| %>
  <div  class="jumbotron p-3 text-white rounded posts__big row">
    <div class="col-md-6 px-0 posts__big-text">
      <h1 class="display-4 font-italic posts__big-title"><%= post.title %></h1>
      <p class="my-3"><% text = strip_tags(post.text) %><%= excerpt(text, 'is', radius: 20) %></p>
      <p class="mb-0"><a href="/posts/<%= post.id %>" class="text-white font-weight-bold"><%= t('read_more') %></a></p>
    </div>
    <% if current_user == post.user %>
      <div class="col-md-6 px-0 buttons">
        <a href="/posts/<%= post.id %>/edit" class="mr-3"><button type="button" class="btn btn-outline-warning"><%= t('edit') %></button></a>
        <%= link_to 'Supprimer', post,  method: :delete, data: { confirm: 'Êtes-vous sur ?' }, class: 'btn btn-outline-danger' %>
      </div>
      <% end %>
    <% if post.image? %>
      <%= image_tag post.image_url(:large), class: 'posts__big-image' %>
    <% else %>
      <img src="<%= image_path('missing-large.jpg') %>" alt="">
    <% end %>
  </div>
<% end %>
<% if @posts.blank? %>
  <div class="text-center">
    <h6><%= t('empty-author') %></h6>
  </div>
<% end %>
</div>